name: "dbt_telecom"
version: "1.0.0"
config-version: 2

profile: "dbt_telecom"

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  dbt_telecom:
    staging:
      +schema: staging
      +materialized: view
    curated:
      +schema: curated
      +materialized: table
    serving:
      +schema: serving
      +materialized: view
